version: "3.8"

services:
  api:
    platform: linux/x86_64
    image: rails-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - postgres
    networks:
      - rails-network
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    stdin_open: true
    tty: true
    command: >
      sh -c "
              echo "INITIALIZING...";
              cp config/database.yml.example config/database.yml;
              rm -rf tmp/pids;
              bash ./bundler.sh;
              bundle exec rails db:create;
              bundle exec rails db:migrate;
              bundle exec rails s -p 3000 -b 0.0.0.0
            "

  redis:
    image: redis:7.0.3-alpine
    container_name: rails-redis
    networks:
      - rails-network
    volumes:
      - rails-redis:/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14.1
    container_name: rails-postgres
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: railsPassword54321
    ports:
      - "5432:5432"
    volumes:
      - rails-postgres:/var/lib/postgresql/data
      - ./tmp:/tmp
    networks:
      - rails-network

networks:
  rails-network:

volumes:
  rails-postgres:
  rails-redis:
  bundle_cache:
