version: "3"
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: railsPassword54321
    ports:
      - "5432:5432" # Expose PostgreSQL port
  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Expose Redis port

volumes:
  postgres_data:
