# create a docker-compose file that runs redis, mysql, and the rails app.
# the rails app should be able to connect to the redis and mysql containers.
# the app should expose the rails port to the host machine.

version: "3.8"

services:
  api:
    platform: linux/x86_64
    image: rails-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - mysql
    #   - redis
    networks:
      - rails-network
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    stdin_open: true
    tty: true
    command: >
      sh -c "
              echo "INITIALIZING...";
              cp config/database.yml.example config/database.yml;
              rm -rf tmp/pids;
              bash ./bundler.sh;
              bundle exec rails db:create;
              bundle exec rails db:migrate;
              bundle exec rails s -p 3000 -b 0.0.0.0
            "

  redis:
    image: redis:7.0.3-alpine
    container_name: rails-redis
    networks:
      - rails-network
    volumes:
      - rails-redis:/data
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.2.0
    container_name: rails-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: rails
      MYSQL_PASSWORD: railsPassword54321
    ports:
      - "3306:3306"
    volumes:
      - rails-mysql:/var/lib/mysql
      - ./tmp:/tmp
    networks:
      - rails-network

networks:
  rails-network:

volumes:
  rails-mysql:
  rails-redis:
  bundle_cache:
